### ISSUE TITLE
Shark soared up out of the water after I hit it by hand (by snow block)

### ISSUE THREAD

**Issue by amadin** [blert2112/mobs_water#2]
Shark soared up out of the water (sea) after I hit it by hand (by snow block) in fly mode. I repeat this bug (but without fly mode) and shark moved with me above my head, then i dived to a depth of sea but shark still flying under sea. 0.4.13-dev with mobs-redo.
![image51](https://cloud.githubusercontent.com/assets/13412191/11101405/c9e70166-88c7-11e5-8cfb-2d566f204c4a.png)

**Comment by blert2112** [comment]
Had thought this was fixed. Will look into it as soon as I can. 
- Chris
