### ISSUE TITLE
Crocodile jumps from the water and then submerged in the water

### ISSUE THREAD

**Issue by amadin** [blert2112/mobs_water#3]
Crocodile jumped from the water and then submerged in the water, cyclically and constantly but in other place other crocodile in more deep sea swimming fine. This jump-effect i saw also at lakes with depth of one block to crocodile and turtle. 0.4.13-dev with mobs-redo.
![image52](https://cloud.githubusercontent.com/assets/13412191/11101874/54b3dc9a-88ca-11e5-92e1-178185ed0a55.png)

**Comment by blert2112** [comment]
This is because there are three different crocs in the mod. One will float and kind of bob up and down in the water. One does not float but instead happily swims around under water. The last one walks the land but if it ends up in water it should not float. 
- Chris

**Comment by amadin** [comment]
I think jumping is too fast (with turtles too). And some crocodiles flying under water and sand.

![image53-krok](https://cloud.githubusercontent.com/assets/13412191/11113635/765e732c-892f-11e5-94be-47be0e65275d.png)

Video - https://yadi.sk/i/2D_mj45vkQD3D
            https://yadi.sk/i/_atL7S7NkQDAg
